### ISSUE TITLE
Package on Flathub outdated

### ISSUE THREAD

**Issue by Orhideous** [flathub/org.musicbrainz.Picard#128]
Update for 2.8.3 #127 has been merged and built successfully, but version in Flathub is [still 2.8.2](https://flathub.org/apps/details/org.musicbrainz.Picard)

**Comment by Lctrs** [comment]
I've triggered a rebuild. Let's see how it goes.

**Comment by mbridon** [comment]
@Lctrs hi, it seems you're taking good care of this app for a while now, do you mind if I stop watching issues so my mailbox can rest a bit ? I don't have time to go back to maintaining apps anymore on Flathub, sorry, life became too complicated recently  and I have to step down, I'll still be available if you need help, just ping me directly though :smiley:

**Comment by Lctrs** [comment]
@mbridon Yeah no problem :)

**Comment by Orhideous** [comment]
> I've triggered a rebuild. Let's see how it goes.

Seems like this didn't help. That's strange…

**Comment by mbridon** [comment]
@Lctrs ok,thank you for understanding and for your work all this time while I've been away :heart:

**Comment by Lctrs** [comment]
@Orhideous Looks like there is just a problem with the appdata somewhere (either it's not up to date on picard side or on flathub side). I've just installed picard from flathub and I got the 2.8.3 version.

**Comment by phw** [comment]
@Lctrs I found the reason, it was my fault. We forgot to update the NEWS.md in the release tag, and the NEWS.md is used to parse the version history for updating the appdata file. We'll get this fixed with the 2.8.4 release. Sorry for the confusion.
