### ISSUE TITLE
Picard closes when hovering over window controls

### ISSUE THREAD

**Issue by phw** [flathub/org.musicbrainz.Picard#137]
From https://tickets.metabrainz.org/browse/PICARD-2578

> When you move the mouse pointer over the button to minimize, maximize or close the window, the application automatically closes.
>
> App installed from flathub.
>
> No errors are displayed in the console in debug mode.

I can reproduce. My suspicion would be that it is related to https://github.com/flathub/org.musicbrainz.Picard/commit/b668505c0d95c6990c6a633f333033b359fb06a7

**Comment by Lctrs** [comment]
You can revert to previous build with this command : 

```
sudo flatpak update --commit=bb6d7337c769beedc58b1eaebf376d81762f32dd5ace6a513edf6944e2cc2414 org.musicbrainz.Picard
```

Does it resolve the issue ?

**Comment by phw** [comment]
@Lctrs Thanks. Running the update also did update [org.kde.WaylandDecoration.QGnomePlatform-decoration](https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration). Afterwards everything worked, also with the latest commit of the Picard package.

I verified, and the fix for the issue came with https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration/pull/8
