### ISSUE TITLE
Picard don't generate Acoustic ID

### ISSUE THREAD

**Issue by zsdedan** [flathub/org.musicbrainz.Picard#138]
Ubuntu 22.04
Picard 2.8.3

When trying to generate an AcousticID, Pickard does nothing. The following entries appear in console:

`E: 12:21:00,393 /app/lib/python3.9/site-packages/picard/acoustid/__init__._on_fpcalc_error:235: Fingerprint calculator failed error= execvp: No such file or directory (0) program='/usr/bin/fpcalc' arguments=['-json', '-length', '120', '/media/music/Music/Various Artists/Touitsu Recordings/[2013-10-19] AniCore/01 - anubasu-anubasu - Setsuna Stream.mp3']
`

**Comment by Lctrs** [comment]
Did you give the flatpak access to your `/media/music` directory ?

**Comment by zsdedan** [comment]
Yes. I'm using flatseal
![image](https://user-images.githubusercontent.com/3087460/196162373-604fbc05-f652-43e5-927c-88509a02f1c8.png)

**Comment by zsdedan** [comment]
Thanks @phw @Lctrs this is solve my problem. Indeed, the wrong path was specified `/usr/bin/fpcalc`
