### ISSUE TITLE
Replay Gain

### ISSUE THREAD

**Issue by ZanderBrown** [flathub/org.musicbrainz.Picard#140]
Any possibility of including the relevant binaries for the replay gain plug-in?

**Comment by phw** [comment]
If so only the [rsgain](https://github.com/complexlogic/rsgain) command should be added for the new [ReplayGain 2.0 plugin](https://community.metabrainz.org/t/new-replaygain-2-0-plugin-released/605702). The old ReplayGain plugin is deprecated and will eventually get completely removed. It also used various now obsolete command line tools for the different formats.

I have also added this utility to the Picard [snap package](https://github.com/metabrainz/picard-snap).

**Comment by Lctrs** [comment]
I'll accept a PR for this.
