### ISSUE TITLE
org.musicbrainz.Picard uses end-of-life runtimes

### ISSUE THREAD

**Issue by rmbleeker** [flathub/org.musicbrainz.Picard#173]
Musicbrainz Picard is using the following runtimes that are end-of-life:

- org.kde.Platform branch 5.15-21.08
- org.freedesktop.Platform.ffmpeg-full branch 21.08
- org.freedesktop.Platform.GL.default branch 21.08

I hope the flatpak can be updated to use newer versions of those runtimes.

**Comment by AJCxZ0** [comment]
Looks like there was work in April 2023 on this for pull request #130 from September 2022 which includes reference to issue #172 which has a comment from @Lctrs four days ago:
> Basically, we're waiting for the release of 5.15-23.08 runtime.

**Comment by arderyp** [comment]
@AJCxZ0 thanks for the references.  Any idea when that runtime they are waiting on is supposed to be released?

**Comment by rmbleeker** [comment]
According to https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/45, it could be released any moment. About a month ago one of the devs said they'd release it "in about a month or something".
