### ISSUE TITLE
No light / dark switching without org.kde.KStyle.Adwaita

### ISSUE THREAD

**Issue by heldderarbeit** [flathub/org.musicbrainz.Picard#200]
Picard is currently not automatically switching between dark and light mode of the app, if you switch on / off the "Dark Style" toggle in Gnome. Only the titlebar changes.

[Screencast from 2024-07-14 01-55-06.webm](https://github.com/user-attachments/assets/2a1c48e9-4d9e-405d-bb61-5ce755c2d8e3)

The last paragraph in this article (https://ubuntuhandbook.org/index.php/2021/10/enable-dark-flatpak-apps-ubuntu-linux-mint/) gave me the right hint. You need to have both org.kde.KStyle.Adwaita
 and org.kde.PlatformTheme.QGnomePlatform installed, but the first one was not automatically installed.

My suggestion would be to add org.kde.KStyle.Adwaita 5.15-23.08 as a dependency to this build. After installing this package, switching between dark / light mode suddenly worked for me.

[Screencast from 2024-07-14 01-57-41.webm](https://github.com/user-attachments/assets/f3b028dc-372e-42bf-a92d-71ed650b6d76)

**Comment by Lctrs** [comment]
This is something that needs to be resolved on flatpak/flathub side.
