### ISSUE TITLE
Can't access files on NTFS mount

### ISSUE THREAD

**Issue by petersaints** [flathub/org.musicbrainz.Picard#3]
I have all my Music stored on an NTFS partition which I also use when I boot into Windows. However, I can't access any of the files with MusicBrainz Picard when I install it using Flatpak (Fedora's version works but it's outdaded). I can't even see the mount point (/mnt/Data) and the symlinks that I have on my home folder are also hidden away from me.

I know that this may have something to do with the way Flatpak isolates applications, but I have other Flatpak applications that are able to access my NTFS partition (e.g., LibreOffice). So it should be possible to change this Flatpak so that it can access it as well.

**Comment by bochecha** [comment]
Does it work when you run the app with `flatpak run --filesystem=/mnt/Data org.musicbrainz.Picard` ?

**Comment by petersaints** [comment]
Yes. That allows me to access my files, both directly by going to /mnt/data or by using the symlinks that I have on my home folder. Thanks for the tip, all I have to do is change the .desktop file to always launch it like this. 

Notwithstanding, this is just a workaround. Is there any way to make it possible to work all the time, regardless of where someone have their files mounted?

**Comment by bochecha** [comment]
> Notwithstanding, this is just a workaround. Is there any way to make it possible to work all the time, regardless of where someone have their files mounted?

I guess long term, what's needed is for Picard to use the "open directory" portal, which allows the user to select a folder on the host system, and then that folder gets passed inside the sandbox.

But that probably would require Picard using a more modern toolkit (Qt5?), and I'm not entirely sure what the state of that portal is.

Unfortunately we're very much in a transition period, where this whole containment technology, and secure ways to "escape" the containment and access the host, are being defined and implemented, so we're probably going to need this kind of workarounds for some time.

In any case, this isn't something we can fix in this specific app build, so I'm going to close the issue.

Thanks for having reported it though, and do open more if you encounter problems. 🙂

**Comment by TingPing** [comment]
Yes the portal support is built into Qt5.
