### ISSUE TITLE
Python packages for plugins missing

### ISSUE THREAD

**Issue by Bendodroid** [flathub/org.musicbrainz.Picard#35]
Greetings,

when trying to install the BPM analyzer plugin for the flatpak build of Picard I get the following error:
```
An error occured while loading the plugin 'bpm':

Plugin 'bpm' : Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/picard/pluginmanager.py", line 258, in _load_plugin_from_directory
    plugin_module = zip_importer.load_module(full_module_name)
  File "/home/userxyz/.var/app/org.musicbrainz.Picard/config/MusicBrainz/Picard/plugins/bpm.zip/bpm/__init__.py", line 20, in <module>
    from aubio import source, tempo
ModuleNotFoundError: No module named 'aubio'
```

When installing Picard via the system package manager, the error can be fixed by installing the `python-aubio` package or by installing aubio via `pip install` system-wide.
Due to the nature of flatpak, this fix doesn't work.
I found a blog post online about the possibility to embed python packages in flatpak apps: https://www.loganasherjones.com/2018/05/using-flatpak-with-python/

Can this package be changed such that the plugin works properly?

**Comment by bochecha** [comment]
Hi @Bendodroid, thank you for the issue.

Plugins are indeed a bit more complex with Flatpak.

We could certainly just add this Python module to Picard. However it's always a delicate balancing act: which modules should we add, which ones should we leave out?

To better gauge this situation, I would like to ask you a few questions first:

1. how did you install the BPM plugin?
2. do you know how popular that plugin is?
3. is that aubio module used for anything else than the BPM plugin?

**Comment by Bendodroid** [comment]
1. Via the settings menu inside Picard itself.
2. No I don't, but as far as I know it is the only plugin to tag bpm values.
3. I do not know.

**Comment by phw** [comment]
To add some details: The aubio plugin is only used by the BPM plugin. We also do not ship this plugin with the Windows and macOS builds, so this plugin does not work there as well. But I actually already thought about bundling this for Windows as well, so I'm not saying this should not be done at all. I probably would already have done so, but last time I tried I hit some issues with building and bundling aubio and gave up.

Having said this, I'm a bit of mixed opninion of whether packaged distributions of Picard such as Flatpak but also the macOS and WIndows builds should include additional modules used by existing plugins.

Ultimately I would like to see some easy way for plugins to bundle their dependencies, but currently we don't have that.

Originally reported at https://tickets.metabrainz.org/browse/PICARD-1613

**Comment by bochecha** [comment]
One thing we could do is package the plugin (and its deps) as a Flatpak extension. It would be called something like `org.musicbrainz.Picard.plugins.BPM` and when running Picard, Flatpak would automatically mount all the installed plugins into the sandbox where Picard would find them.

But that's a lot of work that must be done for every single plugin we want to support. I personally wouldn't be willing to do this work myself as I don't use any plugin for Picard, so someone else would have to do it.

> We also do not ship this plugin with the Windows and macOS builds, so this plugin does not work there as well.

So we're not worse than the official builds. Hurray! :laughing: 

> Ultimately I would like to see some easy way for plugins to bundle their dependencies, but currently we don't have that.

That would be the best solution yes, IMHO. Do you know if there is some work in that direction upstream?

In the meantime, if you know of a (hopefully short) list of the most popular plugins, I guess we could bundle their dependencies, as long as there aren't too many and the work needed is reasonable.

**Comment by Lctrs** [comment]
@bochecha we could move to/use [`flatpak-pip-generator`](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip) to easily manager the python deps.

**Comment by bochecha** [comment]
> @bochecha we could move to/use [`flatpak-pip-generator`](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip) to easily manage the python deps.

I would rather not.

(this ticket is not the place to discuss this though, let's focus on "what" we want to do about plugin dependencies here, we can discuss "how" in a separate ticket)
