### ISSUE TITLE
Plugin "Add Cluster as Release" doesn't work in the Flatpak version

### ISSUE THREAD

**Issue by felipehw** [flathub/org.musicbrainz.Picard#38]
The plugin "Add Cluster as Release" doesn't work in the Flatpak version at my Fedora 30 machine.
If I test the plugin with the RPM version, it works without problems.
But if I test the plugin in the Flatpak version, when I click at "Add Cluster as Release..." nothing happens (normally, it should open your browser at MusicBrainz site populated with information of your cluster).
This plugin is important because it helps to populate the Musicbrainz database ...

**Comment by felipehw** [comment]
I installed and tested the plugin "*Add Cluster as Release*" with `flatpak run -v org.musicbrainz.Picard` but this process doesn't produce any output:
(The lines in the output below were produced when I started the software)
```
$ flatpak run -v org.musicbrainz.Picard 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/dread/.local/share/flatpak
F: Opening user flatpak installation at path /home/dread/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/dread/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2749288135
F: Allocated instance id 2784261026
F: Add defaults in dir /org/musicbrainz/Picard/
F: Add locks in dir /org/musicbrainz/Picard/
F: Allowing homedir access
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/dread/.config/pulse/client.conf': Error opening file /home/dread/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 35 xdg-dbus-proxy --args=37'
F: Running 'bwrap --args 35 picard'
Gtk-Message: 13:48:22.475: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:48:22.475: Failed to load module "pk-gtk-module"
Gtk-Message: 13:48:22.476: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:48:22.476: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: ignoring LC_CTYPE=en_US.UTF-8;LC_NUMERIC=pt_BR.UTF-8;LC_TIME=pt_BR.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=pt_BR.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=pt_BR.UTF-8;LC_NAME=en_US.UTF-8;LC_ADDRESS=en_US.UTF-8;LC_TELEPHONE=en_US.UTF-8;LC_MEASUREMENT=pt_BR.UTF-8;LC_IDENTIFICATION=en_US.UTF-8: not a valid region tag
```

**Comment by bochecha** [comment]
Ok, I got a bit confused by the UI to enable/disable plugins after installing them, but I finally managed to reproduce your issue.

Indeed there's absolutely no output in the terminal. I have no idea what's going on. :confused: 

@phw hi! would you happen to have an idea how we can debug this?

**Comment by bochecha** [comment]
Ok, so looking at the code for the plugin, it seems what it does is create a temporary file (e.g `/tmp/tmplde4bk29.html`) then tries to open it in a web browser.

Opening in a web browser is done in `picard/util/webbrowser2.py`.

That ultimately uses `/usr/lib/python3.7/webbrowser.py`, which I guess is the where the problem is…

**Comment by phw** [comment]
That sounds like it could be a problem. The file is likely created inside the sandbox, and the path is not available to the browser outside.

Other actions that open URLs in the browser work, right?

**Comment by bochecha** [comment]
> Other actions that open URLs in the browser work, right?

They do, yes.

I just tried the following:

```
$ flatpak run --command=python3 org.musicbrainz.Picard 
Python 3.7.4 (default, Nov 10 2011, 15:00:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import webbrowser
>>> webbrowser.open('file://foo.html')
```

Nothing happens at all.

> The file is likely created inside the sandbox, and the path is not available to the browser outside.

That's what I was thinking as well.

Fortunately the file is created in `/tmp`, so if we mount the host `/tmp` into the sandbox, then it works.

So we have a workaround to make the plugin work right now.

However, that's really not a proper long-term solution. I'll need to think about it, maybe ask the Flatpak folks…

**Comment by bochecha** [comment]
@phw woah, that HTML file just contains a form, completely filled-up, and a tiny piece of Javascript which submits the form.

Is there no other way to submit that data? :confused:

**Comment by felipehw** [comment]
Thanks for the awesome support :)
I didn't expect something so fast!
@phw and @bochecha

**Comment by phw** [comment]
> Is there no other way to submit that data? :confused:

Missed the answer to this. If you know a better way that would be great. This is kind of a hack to make a POST work in the browser. If you launch a browser you can easily pass it an URL and have it make a GET request there, but the data that can be provided as URL query parameters is, depending on browser and operating system, limited. SO the issue this plugin ran into was that data got truncated. Generating this local HTML file with all data filled in works around this limitation and allows the data to be then posted to the MB.org server.

**Comment by Lctrs** [comment]
@phw I think that what @bochecha had in mind was an API.

**Comment by bochecha** [comment]
Right, there's no way to do a POST in a browser without resorting to this kind of workarounds. The proper solution would indeed be to have an API endpoint on the MB.org website, and then the form UI would live in Picard, and Picard itself would POST to the servers.

But that requires work on the server, and maybe even in Picard (I have no idea whether Picard gives plugins the ability to implement UI and call the network like this) and I can understand days are too short for everyone.

Back when we were looking at this issue I remember failing to find any magical solution, and that's why I ended up passing the host `/tmp` into the sandbox. It's not great, but it's the only way to make this work without asking others to do lots of work.
