### ISSUE TITLE
Picard doesn't scan files.

### ISSUE THREAD

**Issue by tabetai** [flathub/org.musicbrainz.Picard#56]
I have this error while trying to scan files:

`E: 18:30:58,113 /app/lib/python3.7/site-packages/picard/acoustid/__init__._on_fpcalc_finished:190: Fingerprint calculator failed exit code = 2, exit status = 0, error = Unknown error`

Distro: Pop!_OS 20.04 LTS
Flatpak 1.6.3

**Comment by Lctrs** [comment]
Thanks for reporting this @tabetai. Fix should be available in a couple hours.
