### ISSUE TITLE
Missing discid

### ISSUE THREAD

**Issue by bochecha** [flathub/org.musicbrainz.Picard#6]
See https://community.metabrainz.org/t/discid-missing-on-my-ubuntu-16-04/351056/2

Would be nice if people encountering issues reported them… :disappointed: 

This came up in the Picard 2.0 discussion (#5)

**Comment by Lctrs** [comment]
Well, I don't have any CD player either... :grimacing: 

But if you go to `Help > About` (`Aide > À propos` in french), you can see a message that said that discid is not installed. If you can manage to get a version number for discid instead, I think we're good to go.

**Comment by bochecha** [comment]
![screenshot from 2018-03-27 16-12-12](https://user-images.githubusercontent.com/272170/37972903-a0c2082c-31d9-11e8-99c7-5a869f03f98c.png)

The pull request is coming soon. :slightly_smiling_face:
